var QDATA = [
  { num: 131, passage: "To: All Staff\nFrom: James Wong, Facilities Manager\nSubject: Building Maintenance - Weekend Work\n\nPlease be advised that maintenance work will be ------- (131) ------- in the\neast wing of the building this Saturday, March 16. The work is expected to\ntake approximately six hours and will begin at 8 a.m.\n\nDuring this time, the east wing will be closed to all staff. We ------- (132) -------\nthat you avoid this area and use the west entrance if you need to access the\nbuilding on Saturday. The cafeteria and main lobby will remain open.\n\nWe apologize for any inconvenience. If you have ------- (133) ------- questions,\nplease contact the facilities office at extension 2240 or send an email to\nfacilities@company.com.\n\nThank you for your ------- (134) -------.", desc: "空所(131)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"performed"},{letter:"B",text:"performing"},{letter:"C",text:"perform"},{letter:"D",text:"performance"}], correct: "A", explanation: "maintenance work will be performed で受動態。Aが正解。" },
  { num: 132, desc: "空所(132)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"recommend"},{letter:"B",text:"recommending"},{letter:"C",text:"recommendation"},{letter:"D",text:"recommended"}], correct: "A", explanation: "We recommend that you avoid で recommend が正解。" },
  { num: 133, desc: "空所(133)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"some"},{letter:"B",text:"any"},{letter:"C",text:"much"},{letter:"D",text:"little"}], correct: "B", explanation: "if you have any questions で any が適切。" },
  { num: 134, desc: "空所(134)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"cooperate"},{letter:"B",text:"cooperation"},{letter:"C",text:"cooperative"},{letter:"D",text:"cooperatively"}], correct: "B", explanation: "Thank you for your cooperation で名詞 cooperation。" },
  { num: 135, passage: "Dear Valued Customer,\n\nThank you for your recent order (#8842). We are pleased to ------- (135) -------\nthat your shipment was dispatched today and is on its way to you.\n\nYou can track your delivery using the link below. ------- (136) ------- to our\ntracking page, enter your order number and the email address associated with\nyour account. Estimated delivery is within 3 to 5 business days.\n\nIf you have not received your order within this time frame, please ------- (137) -------\nus immediately. Our customer service team is available Monday through Friday,\n8 a.m. to 6 p.m.\n\nWe appreciate your business and look forward to ------- (138) ------- you again soon.\n\nSincerely,\nThe Sales Team", desc: "空所(135)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"inform"},{letter:"B",text:"informing"},{letter:"C",text:"informed"},{letter:"D",text:"information"}], correct: "A", explanation: "we are pleased to inform you that で to の後は原形。inform。" },
  { num: 136, desc: "空所(136)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"Access"},{letter:"B",text:"Accessing"},{letter:"C",text:"Accessed"},{letter:"D",text:"To access"}], correct: "D", explanation: "To access our tracking page で「〜するには」の不定詞。To access が正解。" },
  { num: 137, desc: "空所(137)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"contact"},{letter:"B",text:"contacting"},{letter:"C",text:"contactable"},{letter:"D",text:"contactless"}], correct: "A", explanation: "please contact us で動詞原形 contact。" },
  { num: 138, desc: "空所(138)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"serve"},{letter:"B",text:"served"},{letter:"C",text:"serving"},{letter:"D",text:"service"}], correct: "C", explanation: "look forward to の後は動名詞。serving が正解。" },
  { num: 139, passage: "The annual employee survey will be conducted from November 1 through November 15.\nYour feedback is extremely ------- (139) ------- to us as we plan for the coming year.\n\nThe survey is anonymous and should take no more than 10 minutes to complete.\n------- (140) ------- you submit your responses by the deadline, we cannot\ninclude your feedback in our report. Please check your email for the survey link.\n\nResults will be ------- (141) ------- at the all-staff meeting in December.\nWe encourage everyone to participate, as your opinions help shape our policies\nand workplace environment.\n\nThank you for taking the time to share your ------- (142) -------.\n\nHuman Resources Department", desc: "空所(139)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"value"},{letter:"B",text:"valuable"},{letter:"C",text:"valuation"},{letter:"D",text:"valued"}], correct: "B", explanation: "Your feedback is extremely valuable で形容詞 valuable。" },
  { num: 140, desc: "空所(140)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"If"},{letter:"B",text:"Unless"},{letter:"C",text:"Although"},{letter:"D",text:"So that"}], correct: "B", explanation: "Unless you submit... we cannot include で「〜しない限り」の Unless。" },
  { num: 141, desc: "空所(141)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"present"},{letter:"B",text:"presented"},{letter:"C",text:"presenting"},{letter:"D",text:"presentation"}], correct: "B", explanation: "Results will be presented で受動態。過去分詞 presented。" },
  { num: 142, desc: "空所(142)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"think"},{letter:"B",text:"thought"},{letter:"C",text:"thoughts"},{letter:"D",text:"thoughtful"}], correct: "C", explanation: "share your thoughts で名詞 thoughts。" },
  { num: 143, passage: "We are excited to announce the opening of our new retail location at 450\nMarket Street. The store will ------- (143) ------- its doors on Saturday,\nDecember 7, at 9 a.m.\n\nTo celebrate, we are offering a 20 percent discount on all purchases made\nduring the opening weekend. ------- (144) -------, the first 100 customers\nwill receive a free gift bag.\n\nWe look forward to welcoming you to our new store. For more information,\nincluding store hours and directions, please visit our website.\n\nThank you for your continued support.", desc: "空所(143)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"open"},{letter:"B",text:"opening"},{letter:"C",text:"opened"},{letter:"D",text:"opens"}], correct: "A", explanation: "The store will open its doors で will の後は原形。open。" },
  { num: 144, desc: "空所(144)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"However"},{letter:"B",text:"Therefore"},{letter:"C",text:"In addition"},{letter:"D",text:"For example"}], correct: "C", explanation: "20%割引に加え先着100名にギフトなので In addition（さらに）が適切。" }
];
