var QDATA = [
  { num: 131, desc: "空所(131)に入る最も適切な語句を選んでください。（パッセージは questions/Part6_TextCompletion.txt 参照）", options: [{letter:"A",text:"performed"},{letter:"B",text:"performing"},{letter:"C",text:"perform"},{letter:"D",text:"performance"}], correct: "A", explanation: "maintenance work will be performed で受動態。Aが正解。" },
  { num: 132, desc: "空所(132)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"recommend"},{letter:"B",text:"recommending"},{letter:"C",text:"recommendation"},{letter:"D",text:"recommended"}], correct: "A", explanation: "We recommend that you avoid で recommend が正解。" },
  { num: 133, desc: "空所(133)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"some"},{letter:"B",text:"any"},{letter:"C",text:"much"},{letter:"D",text:"little"}], correct: "B", explanation: "if you have any questions で any が適切。" },
  { num: 134, desc: "空所(134)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"cooperate"},{letter:"B",text:"cooperation"},{letter:"C",text:"cooperative"},{letter:"D",text:"cooperatively"}], correct: "B", explanation: "Thank you for your cooperation で名詞 cooperation。" },
  { num: 135, desc: "空所(135)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"inform"},{letter:"B",text:"informing"},{letter:"C",text:"informed"},{letter:"D",text:"information"}], correct: "A", explanation: "we are pleased to inform you that で to の後は原形。inform。" },
  { num: 136, desc: "空所(136)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"Access"},{letter:"B",text:"Accessing"},{letter:"C",text:"Accessed"},{letter:"D",text:"To access"}], correct: "D", explanation: "To access our tracking page で「〜するには」の不定詞。To access が正解。" },
  { num: 137, desc: "空所(137)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"contact"},{letter:"B",text:"contacting"},{letter:"C",text:"contactable"},{letter:"D",text:"contactless"}], correct: "A", explanation: "please contact us で動詞原形 contact。" },
  { num: 138, desc: "空所(138)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"serve"},{letter:"B",text:"served"},{letter:"C",text:"serving"},{letter:"D",text:"service"}], correct: "C", explanation: "look forward to の後は動名詞。serving が正解。" },
  { num: 139, desc: "空所(139)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"value"},{letter:"B",text:"valuable"},{letter:"C",text:"valuation"},{letter:"D",text:"valued"}], correct: "B", explanation: "Your feedback is extremely valuable で形容詞 valuable。" },
  { num: 140, desc: "空所(140)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"If"},{letter:"B",text:"Unless"},{letter:"C",text:"Although"},{letter:"D",text:"So that"}], correct: "B", explanation: "Unless you submit... we cannot include で「〜しない限り」の Unless。" },
  { num: 141, desc: "空所(141)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"present"},{letter:"B",text:"presented"},{letter:"C",text:"presenting"},{letter:"D",text:"presentation"}], correct: "B", explanation: "Results will be presented で受動態。過去分詞 presented。" },
  { num: 142, desc: "空所(142)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"think"},{letter:"B",text:"thought"},{letter:"C",text:"thoughts"},{letter:"D",text:"thoughtful"}], correct: "C", explanation: "share your thoughts で名詞 thoughts。" },
  { num: 143, desc: "空所(143)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"open"},{letter:"B",text:"opening"},{letter:"C",text:"opened"},{letter:"D",text:"opens"}], correct: "A", explanation: "The store will open its doors で will の後は原形。open。" },
  { num: 144, desc: "空所(144)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"However"},{letter:"B",text:"Therefore"},{letter:"C",text:"In addition"},{letter:"D",text:"For example"}], correct: "C", explanation: "20%割引に加え先着100名にギフトなので In addition（さらに）が適切。" }
];
