var QDATA = [
  { num: 131, passage: "To: All Department Heads\nFrom: Patricia Kim, HR Director\nSubject: Annual Performance Review – Schedule\n\nPlease be reminded that the annual performance review cycle begins on Monday,\nMarch 4. All managers must complete ------- (131) ------- evaluations for their\ndirect reports by April 15. The evaluation forms are available in the HR\nportal under \"Performance.\"\n\nWe ask that you schedule one-on-one meetings with each employee to discuss\n------- (132) ------- results. Feedback should be constructive and aligned with\nthe goals set at the beginning of the fiscal year. If you need guidance on\nconducting reviews, please attend the optional training session on March 8.\n\nSubmissions received ------- (133) ------- the deadline may delay salary\nadjustments for your team. If you anticipate any difficulty meeting the\ndeadline, please contact the HR team as soon as possible.\n\nThank you for your ------- (134) ------- in this process.\n\nPatricia Kim", desc: "空所(131)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"they"},{letter:"B",text:"their"},{letter:"C",text:"them"},{letter:"D",text:"theirs"}], correct: "B", explanation: "evaluations を修飾する所有格。their が正解。" },
  { num: 132, desc: "空所(132)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"these"},{letter:"B",text:"this"},{letter:"C",text:"that"},{letter:"D",text:"those"}], correct: "A", explanation: "results は複数で前の evaluations を指す。these results が正解。" },
  { num: 133, desc: "空所(133)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"after"},{letter:"B",text:"before"},{letter:"C",text:"within"},{letter:"D",text:"during"}], correct: "A", explanation: "after the deadline で「期限を過ぎて」。遅延の原因になるので after が正解。" },
  { num: 134, desc: "空所(134)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"cooperate"},{letter:"B",text:"cooperation"},{letter:"C",text:"cooperative"},{letter:"D",text:"cooperatively"}], correct: "B", explanation: "Thank you for your cooperation で名詞。「ご協力ありがとう」。cooperation が正解。" },
  { num: 135, passage: "Dear Passengers,\n\nFlight BN204 from Seoul to Singapore has been ------- (135) ------- due to\naircraft maintenance. The new departure time is 4:45 p.m. (local time),\napproximately two hours later than originally scheduled.\n\nPassengers may wait in the lounge or visit the duty-free area. ------- (136) -------,\ncomplimentary refreshments will be available at Gate 22 between 2:30 and 4:00 p.m.\n\nWe apologize for the inconvenience. Passengers connecting to other flights\nshould ------- (137) ------- the ground staff at the gate. We will assist you\nwith rebooking if necessary.\n\nFor the latest updates, please check the flight information display or our\n------- (138) ------- at www.brightair.com.\n\nBright Air Operations", desc: "空所(135)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"delay"},{letter:"B",text:"delayed"},{letter:"C",text:"delaying"},{letter:"D",text:"delays"}], correct: "B", explanation: "has been delayed で受動態。「遅延している」。delayed が正解。" },
  { num: 136, desc: "空所(136)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"However"},{letter:"B",text:"Therefore"},{letter:"C",text:"In addition"},{letter:"D",text:"Otherwise"}], correct: "C", explanation: "追加情報なので In addition（さらに）が適切。" },
  { num: 137, desc: "空所(137)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"contact"},{letter:"B",text:"contacting"},{letter:"C",text:"contacted"},{letter:"D",text:"contact"}], correct: "A", explanation: "should + 動詞原形。contact が正解。" },
  { num: 138, desc: "空所(138)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"website"},{letter:"B",text:"webmaster"},{letter:"C",text:"webpage"},{letter:"D",text:"webbing"}], correct: "A", explanation: "our website で「当社のウェブサイト」。website が正解。" },
  { num: 139, passage: "Q3 Sales Report – Summary\n\nRevenue for the third quarter reached $4.2 million, a 12 percent increase\n------- (139) ------- the same period last year. The growth was driven primarily\nby strong performance in the Asia-Pacific region and new product launches.\n\nOperating expenses remained ------- (140) -------, with a slight decrease in\nmarketing costs. As a result, profit margin improved from 18 percent to 21 percent.\n\nWe ------- (141) ------- that the positive trend will continue in Q4, supported\nby the upcoming holiday season and the new distribution agreement. However,\nwe will continue to monitor supply chain conditions ------- (142) -------.\n\nFull details are available in the attached report.\n\nFinance Team", desc: "空所(139)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"over"},{letter:"B",text:"than"},{letter:"C",text:"above"},{letter:"D",text:"from"}], correct: "A", explanation: "increase over the same period で「前年同月比で」。over が正解。" },
  { num: 140, desc: "空所(140)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"stable"},{letter:"B",text:"stability"},{letter:"C",text:"stabilize"},{letter:"D",text:"stably"}], correct: "A", explanation: "remained の後は形容詞。stable が正解。" },
  { num: 141, desc: "空所(141)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"expect"},{letter:"B",text:"expectation"},{letter:"C",text:"expecting"},{letter:"D",text:"expected"}], correct: "A", explanation: "We expect that で動詞。expect が正解。" },
  { num: 142, desc: "空所(142)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"close"},{letter:"B",text:"closely"},{letter:"C",text:"closer"},{letter:"D",text:"closest"}], correct: "B", explanation: "monitor を修飾する副詞。closely が正解。" },
  { num: 143, passage: "To: All Employees\nFrom: Finance Department\nSubject: Expense Report Reminder\n\nThis is a reminder that all expense reports for business travel and\nconferences completed in October must be ------- (143) ------- by November 10.\n\nPlease submit your reports through the online system and attach all\n------- (144) ------- receipts. Reports submitted after the deadline will\nnot be processed until the following pay cycle, which may delay your\nreimbursement.\n\nIf you have questions about eligible expenses or the submission process,\nplease refer to the expense policy on the intranet or contact the Finance\nhelp desk at finance@company.com.\n\nThank you.", desc: "空所(143)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"submit"},{letter:"B",text:"submitted"},{letter:"C",text:"submitting"},{letter:"D",text:"submission"}], correct: "B", explanation: "must be submitted で受動態。submitted が正解。" },
  { num: 144, desc: "空所(144)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"require"},{letter:"B",text:"required"},{letter:"C",text:"requiring"},{letter:"D",text:"requirement"}], correct: "B", explanation: "required receipts で「必要な領収書」。過去分詞の形容詞用法。required が正解。" }
];
