var QDATA = [
  { num: 131, passage: "To: All Staff\nFrom: James Wong, Facilities Manager\nSubject: Building Maintenance - Weekend Work\n\nPlease be advised that maintenance work will be ------- (131) ------- in the\neast wing of the building this Saturday, March 16. The work is expected to\ntake approximately six hours and will begin at 8 a.m.\n\nDuring this time, the east wing will be closed to all staff. We ------- (132) -------\nthat you avoid this area and use the west entrance if you need to access the\nbuilding on Saturday. The cafeteria and main lobby will remain open.\n\nWe apologize for any inconvenience. If you have ------- (133) ------- questions,\nplease contact the facilities office at extension 2240 or send an email to\nfacilities@company.com.\n\nThank you for your ------- (134) -------.", desc: "空所(131)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"held"},{letter:"B",text:"holding"},{letter:"C",text:"hold"},{letter:"D",text:"holds"}], correct: "A", explanation: "will be held で受動態。「開催される」なので held。" },
  { num: 132, desc: "空所(132)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"encourage"},{letter:"B",text:"encouraging"},{letter:"C",text:"encouragement"},{letter:"D",text:"encouraged"}], correct: "A", explanation: "We encourage you to で動詞原形。encourage が正解。" },
  { num: 133, desc: "空所(133)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"few"},{letter:"B",text:"little"},{letter:"C",text:"many"},{letter:"D",text:"much"}], correct: "A", explanation: "可算名詞の前で「ほとんどない」なら few。a few なら「少しある」。文脈で few が適切。" },
  { num: 134, desc: "空所(134)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"assist"},{letter:"B",text:"assistance"},{letter:"C",text:"assistant"},{letter:"D",text:"assisted"}], correct: "B", explanation: "Thank you for your assistance で名詞 assistance。「ご協力ありがとう」。" },
  { num: 135, passage: "Dear Valued Customer,\n\nThank you for your recent order (#8842). We are pleased to ------- (135) -------\nthat your shipment was dispatched today and is on its way to you.\n\nYou can track your delivery using the link below. ------- (136) ------- to our\ntracking page, enter your order number and the email address associated with\nyour account. Estimated delivery is within 3 to 5 business days.\n\nIf you have not received your order within this time frame, please ------- (137) -------\nus immediately. Our customer service team is available Monday through Friday,\n8 a.m. to 6 p.m.\n\nWe appreciate your business and look forward to ------- (138) ------- you again soon.\n\nSincerely,\nThe Sales Team", desc: "空所(135)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"notify"},{letter:"B",text:"notifying"},{letter:"C",text:"notified"},{letter:"D",text:"notification"}], correct: "A", explanation: "to notify you で to の後は原形。notify が正解。" },
  { num: 136, desc: "空所(136)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"For example"},{letter:"B",text:"However"},{letter:"C",text:"Therefore"},{letter:"D",text:"Moreover"}], correct: "D", explanation: "追加情報なので Moreover（さらに）が適切。" },
  { num: 137, desc: "空所(137)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"submit"},{letter:"B",text:"submitting"},{letter:"C",text:"submitted"},{letter:"D",text:"submission"}], correct: "A", explanation: "please submit で動詞原形。submit が正解。" },
  { num: 138, desc: "空所(138)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"meet"},{letter:"B",text:"met"},{letter:"C",text:"meeting"},{letter:"D",text:"meetings"}], correct: "C", explanation: "look forward to の後は動名詞。meeting が正解。" },
  { num: 139, passage: "The annual employee survey will be conducted from November 1 through November 15.\nYour feedback is extremely ------- (139) ------- to us as we plan for the coming year.\n\nThe survey is anonymous and should take no more than 10 minutes to complete.\n------- (140) ------- you submit your responses by the deadline, we cannot\ninclude your feedback in our report. Please check your email for the survey link.\n\nResults will be ------- (141) ------- at the all-staff meeting in December.\nWe encourage everyone to participate, as your opinions help shape our policies\nand workplace environment.\n\nThank you for taking the time to share your ------- (142) -------.\n\nHuman Resources Department", desc: "空所(139)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"essence"},{letter:"B",text:"essential"},{letter:"C",text:"essentially"},{letter:"D",text:"essentials"}], correct: "B", explanation: "is essential to で「〜に不可欠である」。形容詞 essential。" },
  { num: 140, desc: "空所(140)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"If"},{letter:"B",text:"Unless"},{letter:"C",text:"Although"},{letter:"D",text:"When"}], correct: "B", explanation: "Unless 〜 we cannot「〜しない限りできない」の形。Unless が正解。" },
  { num: 141, desc: "空所(141)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"conduct"},{letter:"B",text:"conducted"},{letter:"C",text:"conducting"},{letter:"D",text:"conduction"}], correct: "B", explanation: "will be conducted で受動態。過去分詞 conducted。" },
  { num: 142, desc: "空所(142)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"consider"},{letter:"B",text:"consideration"},{letter:"C",text:"considerations"},{letter:"D",text:"considered"}], correct: "C", explanation: "your considerations で「ご検討事項」。名詞 considerations。" },
  { num: 143, passage: "We are excited to announce the opening of our new retail location at 450\nMarket Street. The store will ------- (143) ------- its doors on Saturday,\nDecember 7, at 9 a.m.\n\nTo celebrate, we are offering a 20 percent discount on all purchases made\nduring the opening weekend. ------- (144) -------, the first 100 customers\nwill receive a free gift bag.\n\nWe look forward to welcoming you to our new store. For more information,\nincluding store hours and directions, please visit our website.\n\nThank you for your continued support.", desc: "空所(143)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"improve"},{letter:"B",text:"improves"},{letter:"C",text:"improvement"},{letter:"D",text:"improved"}], correct: "C", explanation: "The improvement of で「〜の改善」。名詞 improvement。" },
  { num: 144, desc: "空所(144)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"Similarly"},{letter:"B",text:"Nevertheless"},{letter:"C",text:"Otherwise"},{letter:"D",text:"Instead"}], correct: "A", explanation: "同様の内容を追加するなら Similarly（同様に）が適切。" }
];
