var QDATA = [
  { num: 131, passage: "To: All Contractors\nFrom: Safety Office\nSubject: Mandatory Safety Training – March\n\nAll contractors working on site must complete the annual safety training\n------- (131) ------- March 15. The training is available online through the\ncontractor portal. ------- (132) ------- you complete the training by the\ndeadline, you will not be permitted to work on site until it is done.\n\nThe course takes approximately 45 minutes and covers hazard identification,\nemergency procedures, and proper use of personal protective equipment.\nYour certificate will be ------- (133) ------- to your profile automatically\nupon completion.\n\nIf you have ------- (134) ------- difficulty accessing the portal, contact\nsafety@company.com or call extension 5500.\n\nSafety Office", desc: "空所(131)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"by"},{letter:"B",text:"until"},{letter:"C",text:"for"},{letter:"D",text:"since"}], correct: "A", explanation: "complete ... by March 15 で「3月15日までに完了する」。by が正解。" },
  { num: 132, desc: "空所(132)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"If"},{letter:"B",text:"Unless"},{letter:"C",text:"Although"},{letter:"D",text:"Because"}], correct: "B", explanation: "Unless 〜 you will not be permitted「〜しない限り許可されない」。Unless が正解。" },
  { num: 133, desc: "空所(133)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"add"},{letter:"B",text:"added"},{letter:"C",text:"adding"},{letter:"D",text:"adds"}], correct: "B", explanation: "will be added で受動態。「追加される」。added が正解。" },
  { num: 134, desc: "空所(134)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"some"},{letter:"B",text:"any"},{letter:"C",text:"many"},{letter:"D",text:"much"}], correct: "B", explanation: "have any difficulty で「何か問題があれば」。any が正解。" },
  { num: 135, passage: "Dear Members,\n\nWe are pleased to ------- (135) ------- that the annual membership fee will\nremain unchanged at $120 for the coming year. Renewal notices will be sent\nby email in the first week of December. Payment is due by January 15.\n\n------- (136) -------, we are adding a new benefit: free access to our\nonline webinar library. All renewing members will receive login details\nwith their confirmation. We believe this will add significant ------- (137) -------\nto your membership.\n\nIf you have questions about renewal or the new benefit, please ------- (138) -------\nour member services team at members@club.org.\n\nThank you for your continued support.\n\nMembership Department", desc: "空所(135)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"announce"},{letter:"B",text:"announcing"},{letter:"C",text:"announced"},{letter:"D",text:"announcement"}], correct: "A", explanation: "are pleased to の後は動詞原形。announce が正解。" },
  { num: 136, desc: "空所(136)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"However"},{letter:"B",text:"Therefore"},{letter:"C",text:"In addition"},{letter:"D",text:"Otherwise"}], correct: "C", explanation: "追加情報なので In addition（さらに）が適切。" },
  { num: 137, desc: "空所(137)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"value"},{letter:"B",text:"valuable"},{letter:"C",text:"valuate"},{letter:"D",text:"valuation"}], correct: "A", explanation: "add value to で「〜に価値を加える」。名詞 value が正解。" },
  { num: 138, desc: "空所(138)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"contact"},{letter:"B",text:"contacting"},{letter:"C",text:"contacted"},{letter:"D",text:"contacts"}], correct: "A", explanation: "please の後は動詞原形。contact が正解。" },
  { num: 139, passage: "RE: Supplier Conference – Agenda\n\nThank you for registering for the Supplier Conference on April 10. Below is a\n------- (139) ------- of the day's events. The conference will be held at the\nConvention Center, Hall A. Registration and coffee will begin at 8:00 a.m.\nThe opening session starts at 9:00 a.m.\n\nPlease ensure you arrive ------- (140) ------- to collect your badge and\nmaterials. Lunch will be provided. If you have dietary restrictions, please\nreply to this email by April 3 so we can ------- (141) ------- arrangements.\n\nWe look forward to ------- (142) ------- you at the conference.\n\nEvent Planning Team", desc: "空所(139)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"summary"},{letter:"B",text:"summarize"},{letter:"C",text:"summarizing"},{letter:"D",text:"summarized"}], correct: "A", explanation: "a summary of で「〜の概要」。名詞 summary が正解。" },
  { num: 140, desc: "空所(140)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"early"},{letter:"B",text:"earlier"},{letter:"C",text:"earliest"},{letter:"D",text:"earl"}], correct: "A", explanation: "arrive early で「早めに到着する」。副詞 early が正解。" },
  { num: 141, desc: "空所(141)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"make"},{letter:"B",text:"making"},{letter:"C",text:"made"},{letter:"D",text:"makes"}], correct: "A", explanation: "can の後は動詞原形。make arrangements が正解。" },
  { num: 142, desc: "空所(142)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"see"},{letter:"B",text:"saw"},{letter:"C",text:"seeing"},{letter:"D",text:"seen"}], correct: "C", explanation: "look forward to doing。seeing が正解。" },
  { num: 143, passage: "To: All Tenants\nFrom: Building Management\nSubject: Elevator Maintenance – Building A\n\nPlease be advised that the elevators in Building A will undergo ------- (143) -------\nmaintenance on Sunday, May 19, from 6:00 a.m. to 12:00 p.m. During this time,\nno elevators will be in operation. Stairwells will remain accessible.\n\nWe recommend that you avoid scheduling ------- (144) ------- deliveries or\nmove-ins on this date. If you have already scheduled such activities, please\ncontact the management office to reschedule.\n\nWe apologize for the inconvenience. For questions, call 555-0177.\n\nBuilding Management", desc: "空所(143)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"routine"},{letter:"B",text:"routinely"},{letter:"C",text:"routinize"},{letter:"D",text:"routed"}], correct: "A", explanation: "routine maintenance で「定期保守」。形容詞 routine が正解。" },
  { num: 144, desc: "空所(144)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"large"},{letter:"B",text:"largely"},{letter:"C",text:"larger"},{letter:"D",text:"largest"}], correct: "A", explanation: "large deliveries or move-ins で「大型の配送や引っ越し」。形容詞 large が正解。" }
];
