var QDATA = [
  { num: 131, passage: "To: All Sales Staff\nFrom: Karen Lee, Sales Director\nSubject: Q2 Sales Targets and Incentives\n\nI am writing to remind you that Q2 sales targets have been ------- (131) ------- and are available in the sales portal. Each representative is expected to meet at least 90% of his or her target to qualify for the quarterly bonus. Targets have been set in line with regional forecasts and take into account the product mix and seasonal factors discussed at the last sales conference.\n\nWe have also introduced a new ------- (132) ------- program: the top three performers in each region will receive an additional $500 gift card. Results will be calculated at the end of June based on both volume and margin. If you have questions about how targets are set or need support with your account plans, please contact your regional manager. We will hold a brief Q&A session on April 15 at 10:00 a.m. for anyone who would like clarification.\n\nThank you for your hard work. Let's make Q2 our ------- (133) ------- quarter yet.\n\n------- (134) -------\nKaren Lee", desc: "空所(131)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"post"},{letter:"B",text:"posted"},{letter:"C",text:"posting"},{letter:"D",text:"posts"}], correct: "B", explanation: "have been posted で受動態。「掲示された」。posted が正解。" },
  { num: 132, desc: "空所(132)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"incentive"},{letter:"B",text:"incent"},{letter:"C",text:"incentivize"},{letter:"D",text:"incentives"}], correct: "A", explanation: "a new incentive program で「新たなインセンティブ制度」。incentive が正解。" },
  { num: 133, desc: "空所(133)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"good"},{letter:"B",text:"better"},{letter:"C",text:"best"},{letter:"D",text:"well"}], correct: "C", explanation: "our best quarter yet で「これまでで最高の四半期」。最上級 best が正解。" },
  { num: 134, desc: "空所(134)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"Best regards"},{letter:"B",text:"However"},{letter:"C",text:"For example"},{letter:"D",text:"Therefore"}], correct: "A", explanation: "メールの結び。Best regards が正解。" },
  { num: 135, passage: "Dear Mr. Torres,\n\nThank you for your interest in the Senior Accountant position at Dalton & Associates. We have reviewed your application and credentials and are pleased to invite you to the next stage of our selection process. We would like to ------- (135) ------- you for an interview.\n\nThe interview will focus on your experience with financial reporting, internal controls, and team collaboration. Please reply to this email to ------- (136) ------- a time that works for you. We are available on March 18, 19, or 20 between 9 a.m. and 4 p.m. The interview will take approximately 45 minutes and will be conducted ------- (137) ------- video call. You will receive a calendar invite with the link and dial-in details once the time is confirmed.\n\nIf you have any questions or need to reschedule, please do not hesitate to ------- (138) ------- us. We look forward to meeting you.\n\nSincerely,\nHR Department", desc: "空所(135)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"invite"},{letter:"B",text:"inviting"},{letter:"C",text:"invited"},{letter:"D",text:"invitation"}], correct: "A", explanation: "would like to の後は動詞原形。invite が正解。" },
  { num: 136, desc: "空所(136)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"schedule"},{letter:"B",text:"scheduling"},{letter:"C",text:"scheduled"},{letter:"D",text:"schedules"}], correct: "A", explanation: "to の後は動詞原形。schedule が正解。" },
  { num: 137, desc: "空所(137)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"by"},{letter:"B",text:"with"},{letter:"C",text:"through"},{letter:"D",text:"at"}], correct: "A", explanation: "conducted by video call で「ビデオ通話で行う」。by が正解。" },
  { num: 138, desc: "空所(138)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"contact"},{letter:"B",text:"contacting"},{letter:"C",text:"contacted"},{letter:"D",text:"contacts"}], correct: "A", explanation: "please の後は動詞原形。contact が正解。" },
  { num: 139, passage: "RE: Office Relocation – Update\n\nAs you know, we are relocating to the new building at 200 Commerce Drive. The move is ------- (139) ------- for the weekend of May 10–11. All staff should have packed their personal items and cleared their desks by Friday, May 9. IT will disconnect computers on the afternoon of May 9 and will restore services at the new location by the morning of May 12. Moving crews will handle all furniture and equipment; please do not attempt to move heavy items yourself.\n\nOn Monday, May 12, please report ------- (140) ------- to the new building. Your new desk assignment and floor plan are available on the intranet under \"Relocation.\" Parking permits for the new garage will be distributed ------- (141) ------- the HR desk on May 12 and 13. If you use public transit, note that the building is a five-minute walk from the Central Station exit.\n\nIf you have ------- (142) ------- questions, contact the relocation team at relocation@company.com.\n\nFacilities Management", desc: "空所(139)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"schedule"},{letter:"B",text:"scheduled"},{letter:"C",text:"scheduling"},{letter:"D",text:"schedules"}], correct: "B", explanation: "is scheduled for で「〜の予定である」。scheduled が正解。" },
  { num: 140, desc: "空所(140)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"direct"},{letter:"B",text:"directly"},{letter:"C",text:"direction"},{letter:"D",text:"directive"}], correct: "B", explanation: "report を修飾する副詞。directly が正解。「直接新しいビルへ出社してください」。Bが正解。" },
  { num: 141, desc: "空所(141)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"at"},{letter:"B",text:"in"},{letter:"C",text:"on"},{letter:"D",text:"by"}], correct: "A", explanation: "at the HR desk で「HR デスクで」。at が正解。" },
  { num: 142, desc: "空所(142)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"some"},{letter:"B",text:"any"},{letter:"C",text:"much"},{letter:"D",text:"few"}], correct: "B", explanation: "If you have any questions で「ご質問があれば」。any が正解。" },
  { num: 143, passage: "To: All Department Heads\nFrom: Finance\nSubject: Budget Submission – Fiscal Year 2025\n\nDepartmental budgets for fiscal year 2025 must be ------- (143) ------- through the budget portal by 5 p.m. on Friday, April 4. Late submissions will not be considered in the first round of allocations. The portal will close automatically at the deadline; no extensions will be granted except in cases of documented system failure.\n\nPlease use the template provided and include a ------- (144) ------- for any increase over last year's budget. All requests over 10% must be approved by the CFO before submission. Supporting documentation such as quotes or business cases should be attached where applicable.\n\nIf you need access to the portal or have technical issues, contact finance@company.com. We will hold office hours on April 2 and 3 for anyone who needs assistance.\n\nFinance Department", desc: "空所(143)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"submit"},{letter:"B",text:"submitted"},{letter:"C",text:"submitting"},{letter:"D",text:"submission"}], correct: "B", explanation: "must be submitted で受動態。submitted が正解。" },
  { num: 144, desc: "空所(144)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"justify"},{letter:"B",text:"justification"},{letter:"C",text:"justified"},{letter:"D",text:"justifiable"}], correct: "B", explanation: "include a justification for で「〜の正当性の説明を含める」。名詞 justification が正解。" }
];
