var QDATA = [
  { num: 131, passage: "To: All Department Heads\nFrom: Patricia Lee, HR Director\nSubject: Annual Performance Reviews\n\nThe annual performance review process will ------- (131) ------- from March 1 through March 31.\nManagers are asked to ------- (132) ------- one-on-one meetings with each team member.\n\nPlease use the ------- (133) ------- evaluation form available in the HR portal. Completed\nforms must be submitted by March 31. Your ------- (134) ------- in this process is essential\nfor fair and consistent feedback across the company.\n\nThank you for your cooperation.", desc: "空所(131)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"run"},{letter:"B",text:"running"},{letter:"C",text:"runs"},{letter:"D",text:"have run"}], correct: "A", explanation: "will run で「実施される」。will の後は動詞原形。" },
  { num: 132, desc: "空所(132)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"schedule"},{letter:"B",text:"scheduling"},{letter:"C",text:"scheduled"},{letter:"D",text:"schedules"}], correct: "A", explanation: "are asked to の後は動詞原形。schedule が正解。" },
  { num: 133, desc: "空所(133)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"standard"},{letter:"B",text:"standardize"},{letter:"C",text:"standardization"},{letter:"D",text:"standardly"}], correct: "A", explanation: "形容詞 standard で「標準の」。standard evaluation form。" },
  { num: 134, desc: "空所(134)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"participate"},{letter:"B",text:"participation"},{letter:"C",text:"participating"},{letter:"D",text:"participant"}], correct: "B", explanation: "Your participation in で「ご参加」。名詞 participation。" },
  { num: 135, passage: "Dear Passengers,\n\nWe are writing to ------- (135) ------- you that Flight 442 to Seattle has been delayed\nby approximately two hours due to adverse weather conditions.\n\n------- (136) ------- the delay, we will provide complimentary refreshments at the gate.\nWe apologize for any inconvenience and thank you for your ------- (137) -------.\n\nFor updates, please check the flight status on our website or ------- (138) ------- the\ninformation desk.\n\nPacific Airways", desc: "空所(135)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"inform"},{letter:"B",text:"informing"},{letter:"C",text:"informed"},{letter:"D",text:"information"}], correct: "A", explanation: "to inform you that で to の後は原形。inform が正解。" },
  { num: 136, desc: "空所(136)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"Despite"},{letter:"B",text:"In spite"},{letter:"C",text:"Because"},{letter:"D",text:"Due to"}], correct: "D", explanation: "Due to the delay で「遅延のため」。理由を表す。" },
  { num: 137, desc: "空所(137)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"patient"},{letter:"B",text:"patience"},{letter:"C",text:"patiently"},{letter:"D",text:"patience"}], correct: "B", explanation: "Thank you for your patience で「ご辛抱ありがとう」。名詞。" },
  { num: 138, desc: "空所(138)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"contact"},{letter:"B",text:"contacting"},{letter:"C",text:"contacted"},{letter:"D",text:"contact"}], correct: "A", explanation: "please の後、or で並列。contact が動詞原形で正解。" },
  { num: 139, passage: "The quarterly sales report ------- (139) ------- that revenue exceeded projections by 12 percent.\n------- (140) -------, operating costs remained within budget.\n\nThe Asia-Pacific region showed the strongest growth. We ------- (141) ------- to maintain\nthis momentum in the next quarter. A detailed breakdown is ------- (142) ------- in the\nappendix.\n\nFinance Department", desc: "空所(139)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"indicate"},{letter:"B",text:"indicates"},{letter:"C",text:"indicating"},{letter:"D",text:"indicated"}], correct: "B", explanation: "The report indicates that で三人称単数。indicates が正解。" },
  { num: 140, desc: "空所(140)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"However"},{letter:"B",text:"Furthermore"},{letter:"C",text:"Therefore"},{letter:"D",text:"Otherwise"}], correct: "B", explanation: "追加情報なので Furthermore（さらに）。" },
  { num: 141, desc: "空所(141)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"expect"},{letter:"B",text:"expects"},{letter:"C",text:"expecting"},{letter:"D",text:"expected"}], correct: "A", explanation: "We expect to で「〜することを期待している」。原形 expect。" },
  { num: 142, desc: "空所(142)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"provide"},{letter:"B",text:"provided"},{letter:"C",text:"providing"},{letter:"D",text:"provision"}], correct: "B", explanation: "is provided で受動態。「添付資料に記載されている」。provided。" },
  { num: 143, passage: "Reminder: The deadline for submitting travel expense reports is the last day of each month.\n------- (143) ------- reports received after this date will be processed in the following\npay period.\n\nPlease ------- (144) ------- that all receipts are attached and the report is signed by\nyour supervisor before submission.\n\nAccounting Department", desc: "空所(143)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"Late"},{letter:"B",text:"Lately"},{letter:"C",text:"Later"},{letter:"D",text:"Latest"}], correct: "A", explanation: "Late reports で「遅れて提出された報告書」。形容詞 Late。" },
  { num: 144, desc: "空所(144)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"confirm"},{letter:"B",text:"confirming"},{letter:"C",text:"confirmation"},{letter:"D",text:"confirmed"}], correct: "A", explanation: "Please confirm that で動詞原形。confirm が正解。" }
];
