var QDATA = [
  { num: 131, desc: "空所(131)に入る最も適切な語句を選んでください。\n（パッセージはメール・社内通知を想定）", options: [{letter:"A",text:"scheduled"},{letter:"B",text:"scheduling"},{letter:"C",text:"schedule"},{letter:"D",text:"schedules"}], correct: "A", explanation: "The meeting is scheduled to で「会議は〜の予定です」。過去分詞 scheduled。" },
  { num: 132, desc: "空所(132)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"attend"},{letter:"B",text:"attending"},{letter:"C",text:"attendance"},{letter:"D",text:"attended"}], correct: "A", explanation: "please attend で「出席してください」。動詞原形 attend。" },
  { num: 133, desc: "空所(133)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"this"},{letter:"B",text:"these"},{letter:"C",text:"that"},{letter:"D",text:"those"}], correct: "B", explanation: "these は直前の複数名詞を指す。these changes などが自然。" },
  { num: 134, desc: "空所(134)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"respond"},{letter:"B",text:"response"},{letter:"C",text:"responsive"},{letter:"D",text:"responsively"}], correct: "B", explanation: "Thank you for your response で「ご返信ありがとうございます」。名詞 response。" },
  { num: 135, desc: "空所(135)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"confirm"},{letter:"B",text:"confirming"},{letter:"C",text:"confirmed"},{letter:"D",text:"confirmation"}], correct: "A", explanation: "we are pleased to confirm で to の後は原形。confirm。" },
  { num: 136, desc: "空所(136)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"Additional"},{letter:"B",text:"Additionally"},{letter:"C",text:"Addition"},{letter:"D",text:"Add"}], correct: "A", explanation: "Additional は形容詞で「追加の」。Additional information が自然。" },
  { num: 137, desc: "空所(137)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"provide"},{letter:"B",text:"providing"},{letter:"C",text:"provided"},{letter:"D",text:"provision"}], correct: "A", explanation: "please provide で動詞原形。provide が正解。" },
  { num: 138, desc: "空所(138)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"hear"},{letter:"B",text:"heard"},{letter:"C",text:"hearing"},{letter:"D",text:"hears"}], correct: "C", explanation: "look forward to の後は動詞-ing。hearing が正解。" },
  { num: 139, desc: "空所(139)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"importance"},{letter:"B",text:"important"},{letter:"C",text:"importantly"},{letter:"D",text:"import"}], correct: "B", explanation: "is important to で「〜にとって重要である」。形容詞 important。" },
  { num: 140, desc: "空所(140)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"Because"},{letter:"B",text:"Because of"},{letter:"C",text:"Therefore"},{letter:"D",text:"However"}], correct: "C", explanation: "前文の結果として「したがって」なら Therefore。文頭の接続副詞。" },
  { num: 141, desc: "空所(141)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"hold"},{letter:"B",text:"held"},{letter:"C",text:"holding"},{letter:"D",text:"holds"}], correct: "B", explanation: "will be held で受動態。「開催される」なので held。" },
  { num: 142, desc: "空所(142)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"suggest"},{letter:"B",text:"suggestion"},{letter:"C",text:"suggestions"},{letter:"D",text:"suggested"}], correct: "C", explanation: "your suggestions で「あなたの提案」。複数形 suggestions が自然。" },
  { num: 143, desc: "空所(143)に入る最も適切な語句を選んでください。\n例: The ------- of the training program is next week.", options: [{letter:"A",text:"begin"},{letter:"B",text:"begins"},{letter:"C",text:"beginning"},{letter:"D",text:"began"}], correct: "C", explanation: "The beginning of で「〜の開始」。名詞 beginning が正解。" },
  { num: 144, desc: "空所(144)に入る最も適切な語句を選んでください。", options: [{letter:"A",text:"Furthermore"},{letter:"B",text:"However"},{letter:"C",text:"Otherwise"},{letter:"D",text:"Therefore"}], correct: "A", explanation: "追加情報を述べるので Furthermore（さらに）が適切。" }
];
